appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: avEAUMDRJv5h97bESx4OWFI2U42REEG4kO3dNoMVR7xqsQyIGOS3VYSsWdnWFSo82trQwH0R1tTAR6mBBRwLZjtBAQe/0rBD4EcJptMmzEhKlpUya59kG/AqpDVAv6AIDg1qD64XehYNVuCYoIL5AxdOaMRm6VPr6j5A/D7EELQXCQ/GgAQibZEXozgkL81FKLmkSxSpIaUGr9SxxtSpJczwmJWlGEOCHA0+B1hh8ZBmM59x7/8PsCR+DEzktUwUglazehi899LW6yeki9zf21rXQCgN2od5K4/Y/ezuieF2P1n1IbAtrcWbaghgpOdonijNB0ycAYeSgB+NWERneiIyQXAkZUu32w2Q9SMsgb4o784j8DY6V75zscxHU8ZlV1HindjkcytiP/bQw6yCFF1cNEw++RdPNHqp6O9juDVNKYa2OSmTxuua1erDq0PZr3bf+HHpEd51GyBIkGXzIpizh3A7oaw7phc6Hci1QJSDICUi53kdNO4PKWLUj9rrwKD9oR+MQatol171yXP3Z5gZfB6qEhW1df52s/Cu52Assq5vZ4kGE2BV0ytggRfmVnQa+0gWvY8kfDBtnOIcvAzClwdpupHhgBULg1Pyn/DD0BA8sj5w8gbLGdSkts+g7+Ehft1yrxLSGkAL1HZ3TDto73m1Mq53F00iRT0HqZ0=}
bot:
  automerge: true
